# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "gst-starter"
client_id = "c00a5c3a5ce1572b5e4fd98f8b266d03"
application_url = "https://andreas-call-competitions-gates.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://andreas-call-competitions-gates.trycloudflare.com/auth/callback",
  "https://andreas-call-competitions-gates.trycloudflare.com/auth/shopify/callback",
  "https://andreas-call-competitions-gates.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "storetools-beta.myshopify.com"
